# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/PytLab/"
  weibo: "http://weibo.com/shaowugui "
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/shao-zheng-jiang"
  #douban: "#"
  mail: "mailto:shaozhengjiang@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: ''
favicon: /assets/images/favicon/icon.png

#你的头像url
avatar: /assets/images/avatar/Floe.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "pytlab"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  iPytLab.com: http://ipytlab.com
#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 喜欢写代码的，希望能靠自己的代码发出文章来的，科狗一只 (ง •̀_•́)ง
